name: Build CI Buildbox Images
run-name: Build CI Buildbox Images
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-ci-buildbox-images.yaml
      - build.assets/Dockerfile
      - build.assets/Dockerfile-arm
      - build.assets/Dockerfile-centos7
      - build.assets/Dockerfile-centos7-fips
      - build.assets/Dockerfile-node
      - build.assets/Makefile
      - build.assets/images.mk
      - build.assets/versions.mk
    branches:
      - master
      - branch/**

env:
  REGISTRY: ghcr.io

jobs:
  buildbox:
    strategy:
      matrix:
        include:
          - target: buildbox
          - target: buildbox-arm
          - target: buildbox-centos7
          - target: buildbox-centos7-fips
          - target: buildbox-centos7
            arch: arm64
            builder: '{"group": "prod", "labels": ["self-hosted", "linux", "arm64"]}'
          - target: buildbox-centos7-fips
            arch: arm64
            builder: '{"group": "prod", "labels": ["self-hosted", "linux", "arm64"]}'
          - target: buildbox-node

    name: Build Buildbox (${{ matrix.target }})
    #runs-on: ${{ matrix.builder || 'ubuntu-22.04-32core' }}
    runs-on: ${{ matrix.builder || 'ubuntu-latest' }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # We need to keep env vars in sync, so, we can't use standard build actions
      - name: Build and push buildbox image
        env:
          ARCH: ${{ matrix.arch || 'amd64' }}
          TARGET: ${{ matrix.target }}
        run: |
          echo make -s -C build.assets "${TARGET}" PUSH=1 ARCH="${ARCH}" >> "$GITHUB_STEP_SUMMARY"
