name: Reproduce Mac upload-artifact failure
on:
  push:
    branches:
      - camh/repro-mac-upload-artifact-issue

jobs:
  test-upload-artifact:
    runs-on: macos-13-xl-arm64
    steps:
      - name: Create files (500MiB)
        run: |
          dd if=/dev/urandom of=artifact bs=1M count=500
          dd if=/dev/zero of=artifact-unsigned bs=1M count=1
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: urandom
          compression-level: 0
          retention-days: 1
          path: |
            artifact
            !*-unsigned*
